cloud:
  aws:
    credentials:
      access-key: AKIAS4RJWBS4Y47APSNE
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: bird-trading-platform


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

